name: CI

on:
  pull_request:
    branches:
      - master
      - release-*
      -

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 5
      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Remove existing TypeScript
        run: |
          npm uninstall typescript --no-save
          npm uninstall tslint --no-save
      - name: Create DB
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port 32574 -uroot -proot -e "CREATE DATABASE cube;"
          mysql --host 127.0.0.1 --port 32574 -uroot -proot -e "SHOW DATABASES"
          mysql --host 127.0.0.1 --port 32574 -uroot -proot -e "SET GLOBAL sql_mode = '';"
      - name: npm install and test
        run: |
          cp .env.example .env
          npm install
          npm update
          npm run build:ci
