name: CI

on:
  pull_request:
    branches:
      - master
      - release-*
      -

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 5
      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Remove existing TypeScript
        run: |
          npm uninstall typescript --no-save
          npm uninstall tslint --no-save
      - name: Set up MySQL 5.7
        uses: mirromutth/mysql-action@master
        with:
          mysql version: 5.7
          mysql database: cube
          mysql root_password: root
      - name: npm install and test
        run: |
          cp .env.example .env
          npm install
          npm update
          npm run build:ci
