name: CI

on:
  pull_request:
    branches:
      - master
      - release-*
      -

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: cube
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 5
      - name: Set up MySQL 5.7
          uses: mirromutth/mysql-action@master
          with:
            mysql_version: 5.7
            mysql_database: cube
            mysql_root_password: root
      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Remove existing TypeScript
        run: |
          npm uninstall typescript --no-save
          npm uninstall tslint --no-save
      - name: npm install and test
        run: |
          cp .env.example .env
          npm install
          npm update
          npm run build:ci
